version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=
      - ALLOWED_GROUP_ID=
      - ADMINS=
      - CHARACTER_AI_TOKEN=
    volumes:
      # Монтируем локальный файл hall.csv
      - ./hall.csv:/app/hall.csv
    restart: always