apiVersion: v2
name: smule-bot
description: A Helm chart for Smule Telegram Bot
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - telegram
  - bot
  - smule
  - monitoring
home: https://github.com/nlemeshko/dsipsmule-bot
sources:
  - https://github.com/nlemeshko/dsipsmule-bot
maintainers:
  - name: nlemeshko
    email: nlemeshko@example.com
